### ISSUE TITLE
Object literal may only specify known properties, and 'memoizeOptions' does not exist in type

### ISSUE THREAD

**Issue by miliko0022** [planttheidea/selectorator#42]
this my code

```
import { createSelector } from '@reduxjs/toolkit'

const selectNumCompletedTodos2 = createSelector(
    (state: RootState) => state.counter.ok.ok,
    (state: RootState) => state.counter.ok.ok,
    (ok: number, ok1: number) => `${ok} + ${ok1}`,
    {

        memoizeOptions: {
            equalityCheck: (a, b) => {
                return a === b;
            },
        }
    }
)
```

I get this error

>The last overload gave the following error. Argument of type '{ memoizeOptions: { equalityCheck: (a: any, b: any) => boolean; }; }' is not assignable to parameter of type '(res1: number, res2: number, res3: string) => unknown'. Object literal may only specify known properties, and 'memoizeOptions' does not exist in type '(res1: number, res2: number, res3: string) => unknown'.

**Comment by planttheidea** [comment]
I would recommend reaching out to the [Redux Toolkit](https://github.com/reduxjs/redux-toolkit) team then. Your example does not appear to use `selectorator` at all, so it is better answered there.

**Comment by miliko0022** [comment]
sorry bro didn't go there
